spring:
  application:
    name: cloud-storage
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
logging:
  level:
    root: info
    dev.yoxaron.cloudstorage: debug
    org.hibernate.sql: debug
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"