spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud-storage-db
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: user-files