spring:
  application:
    name: cloud-storage
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  session:
    timeout: 60m
    data:
      redis:
        namespace: cloud-storage:session
        flush-mode: on_save
  data:
    redis:
      timeout: 2s
server:
  tomcat:
    max-part-count: 100
logging:
  level:
    root: info
    dev.yoxaron.cloudstorage: debug
    org.hibernate.sql: debug
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"